In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
path_2012 = r"H:\Python\3°etapa\Atividade 6\Tabela5-sem_emprego_2012.csv"
path_2026 = r"H:\Python\3°etapa\Atividade 6\Tabela5-sem_emprego_2026.csv"
path_horas = r"H:\Python\3°etapa\Atividade 6\Tabela 1.1.1.xls"

In [5]:
tab_2012 = pd.read_csv(path_2012, encoding="utf8", sep=";", decimal=",")

In [6]:
tab_2012 = tab_2012.rename(columns={"Descupados - Homens (2012 T1)" : "homens_2012"})
tab_2012 = tab_2012.rename(columns={"Desocupados - Mulheres (2012 T1)" : "mulheres_2012"})

In [7]:
tab_2012

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1)
0,AC,12,Acre,45.3,54.7
1,AL,27,Alagoas,44.7,55.3
2,AM,13,Amazonas,47.5,52.5
3,AP,16,Amapá,48.1,51.9
4,BA,29,Bahia,43.8,56.2
5,CE,23,Ceará,51.1,48.9
6,DF,53,Distrito Federal,41.0,59.0
7,ES,32,Espírito Santo,46.4,53.6
8,GO,52,Goiás,41.0,59.0
9,MA,21,Maranhão,47.2,52.8
10,MG,31,Minas Gerais,43.1,56.9
11,MS,50,Mato Grosso do Sul,47.2,52.8
12,MT,51,Mato Grosso,44.1,55.9
13,PA,15,Pará,43.2,56.8
14,PB,25,Paraíba,44.4,55.6
15,PE,26,Pernambuco,43.9,56.1
16,PI,22,Piauí,51.2,48.8
17,PR,41,Paraná,40.3,59.7
18,RJ,33,Rio de Janeiro,44.2,55.8
19,RN,24,Rio Grande do Norte,51.0,49.0
20,RO,11,Rondônia,43.4,56.6
21,RR,14,Roraima,41.8,58.2
22,RS,43,Rio Grande do Sul,42.8,57.2
23,SC,42,Santa Catarina,42.7,57.3
24,SE,28,Sergipe,46.5,53.5
25,SP,35,São Paulo,45.4,54.6
26,TO,17,Tocantins,55.3,44.7

In [8]:
tab_2026 = pd.read_csv(path_2026, encoding="utf8", sep=";")

In [9]:
tab_2026 = tab_2026.rename(columns={"Desocupados - Homens (2026 T1)" : "homens_2026"})
tab_2026 = tab_2026.rename(columns={"Desocupados - Mulheres (2026 T1)" : "mulheres_2026"})

In [10]:
estado = "Minas Gerais"

In [11]:
tab_2026

,Sigla,Código,Estado,Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,"53,2","46,8"
1,AL,27,Alagoas,"50,7","49,3"
2,AM,13,Amazonas,"46,8","53,2"
3,AP,16,Amapá,"51,1","48,9"
4,BA,29,Bahia,"44,7","55,3"
5,CE,23,Ceará,"52,7","47,3"
6,DF,53,Distrito Federal,"47,9","52,1"
7,ES,32,Espírito Santo,"47,5","52,5"
8,GO,52,Goiás,"47,5","52,5"
9,MA,21,Maranhão,"49,1","50,9"
10,MG,31,Minas Gerais,"48,6","51,4"
11,MS,50,Mato Grosso do Sul,"45,3","54,7"
12,MT,51,Mato Grosso,"42,8","57,2"
13,PA,15,Pará,"48,3","51,7"
14,PB,25,Paraíba,"48,9","51,1"
15,PE,26,Pernambuco,"48,7","51,3"
16,PI,22,Piauí,"55,1","44,9"
17,PR,41,Paraná,"46,3","53,7"
18,RJ,33,Rio de Janeiro,"45,4","54,6"
19,RN,24,Rio Grande do Norte,"48,2","51,8"
20,RO,11,Rondônia,33,67
21,RR,14,Roraima,"43,4","56,6"
22,RS,43,Rio Grande do Sul,"47,4","52,6"
23,SC,42,Santa Catarina,"44,6","55,4"
24,SE,28,Sergipe,"40,3","59,7"
25,SP,35,São Paulo,"46,2","53,8"
26,TO,17,Tocantins,"46,2","53,8"

In [12]:
comp = tab_2012.merge(tab_2026, on = ["Sigla", "Código", "Estado"], how = "inner")

In [13]:
indicador_1 = pd.read_excel(path_horas, engine="xlrd")
indicador_1 = pd.read_excel(path_horas, engine="xlrd", header=None)

In [14]:
indicador_1 = indicador_1.iloc[8:41].copy()
indicador_1.columns = [
    "uf_regiao",
    "total",
    "total_branca",
    "total_preta_parda",
    "homem_branca",
    "homem_preta_parda",
    "mulher_branca",
    "mulher_preta_parda",
]
indicador_1 = indicador_1.reset_index(drop=True)

In [15]:
indicador_1

,uf_regiao,total,total_branca,total_preta_parda,homem_branca,homem_preta_parda,mulher_branca,mulher_preta_parda
0,Brasil,16.985781,16.54593,17.333142,11.705136,11.74633,20.404106,22.037998
1,Norte,16.187037,15.925246,16.256032,11.588653,11.514646,19.29578,20.534188
2,Rondônia,17.014162,16.727733,17.101523,12.111127,12.54408,20.412887,21.06141
3,Acre,13.606903,13.806929,13.541399,10.79612,9.686983,16.130352,16.710754
4,Amazonas,16.80729,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
5,Roraima,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
6,Pará,16.474268,16.181627,16.560239,11.524306,11.026707,19.83511,21.591144
7,Amapá,13.586656,14.38918,13.415091,11.116821,10.749444,16.648579,15.908487
8,Tocantins,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399
9,Nordeste,18.499396,18.1517,18.610911,11.723907,11.848436,22.744666,23.716716
10,Maranhão,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
11,Piauí,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.69544
12,Ceará,19.499293,18.52712,19.882469,12.186936,12.821323,23.019718,24.952274
13,Rio Grande do Norte,18.30774,18.101853,18.445218,11.166909,11.086286,23.54708,24.422884
14,Paraíba,18.920816,18.88792,18.945306,12.480204,12.400831,23.642936,24.03565
15,Pernambuco,19.306249,18.950219,19.418444,12.312833,12.868821,23.35788,24.243396
16,Alagoas,20.217129,19.165111,20.560451,12.121839,13.35716,24.093655,25.856637
17,Sergipe,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
18,Bahia,17.849776,17.538007,17.935566,10.551673,10.982808,22.57273,23.217119
19,Sudeste,17.104218,16.834863,17.397989,11.933522,12.180843,20.732969,21.990431
20,Minas Gerais,17.502141,17.179387,17.707564,11.31972,11.61912,22.18665,23.075751
21,Espírito Santo,17.111106,16.51061,17.478861,11.798571,12.017589,20.464462,22.196626
22,Rio de Janeiro,16.716263,16.097467,17.24306,12.000036,12.864896,19.203741,20.957728
23,São Paulo,17.071295,16.964437,17.25548,12.123044,12.2352,20.771186,21.76762
24,Sul,15.527769,15.570983,15.406088,11.546629,11.159487,19.012969,19.338734
25,Paraná,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.36538
26,Santa Catarina,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
27,Rio Grande do Sul,15.356709,15.337269,15.448203,11.308447,11.519941,18.86823,19.10772
28,Centro-Oeste,15.000763,14.826985,15.078025,10.546799,10.332059,18.220683,19.33104
29,Mato Grosso do Sul,15.309783,14.902105,15.567204,10.446213,11.12692,18.5932,19.542761
30,Mato Grosso,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
31,Goiás,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
32,Distrito Federal,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332

In [16]:
regioes = ["Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste"]

estado = indicador_1[~indicador_1["uf_regiao"].isin(["Brasil"] + regioes)]

estado = estado.rename(columns={"uf_regiao" : "Estado"}).reset_index(drop=True)

In [17]:
estado

,Estado,total,total_branca,total_preta_parda,homem_branca,homem_preta_parda,mulher_branca,mulher_preta_parda
0,Rondônia,17.014162,16.727733,17.101523,12.111127,12.54408,20.412887,21.06141
1,Acre,13.606903,13.806929,13.541399,10.79612,9.686983,16.130352,16.710754
2,Amazonas,16.80729,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
3,Roraima,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
4,Pará,16.474268,16.181627,16.560239,11.524306,11.026707,19.83511,21.591144
5,Amapá,13.586656,14.38918,13.415091,11.116821,10.749444,16.648579,15.908487
6,Tocantins,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399
7,Maranhão,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
8,Piauí,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.69544
9,Ceará,19.499293,18.52712,19.882469,12.186936,12.821323,23.019718,24.952274
10,Rio Grande do Norte,18.30774,18.101853,18.445218,11.166909,11.086286,23.54708,24.422884
11,Paraíba,18.920816,18.88792,18.945306,12.480204,12.400831,23.642936,24.03565
12,Pernambuco,19.306249,18.950219,19.418444,12.312833,12.868821,23.35788,24.243396
13,Alagoas,20.217129,19.165111,20.560451,12.121839,13.35716,24.093655,25.856637
14,Sergipe,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
15,Bahia,17.849776,17.538007,17.935566,10.551673,10.982808,22.57273,23.217119
16,Minas Gerais,17.502141,17.179387,17.707564,11.31972,11.61912,22.18665,23.075751
17,Espírito Santo,17.111106,16.51061,17.478861,11.798571,12.017589,20.464462,22.196626
18,Rio de Janeiro,16.716263,16.097467,17.24306,12.000036,12.864896,19.203741,20.957728
19,São Paulo,17.071295,16.964437,17.25548,12.123044,12.2352,20.771186,21.76762
20,Paraná,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.36538
21,Santa Catarina,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
22,Rio Grande do Sul,15.356709,15.337269,15.448203,11.308447,11.519941,18.86823,19.10772
23,Mato Grosso do Sul,15.309783,14.902105,15.567204,10.446213,11.12692,18.5932,19.542761
24,Mato Grosso,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
25,Goiás,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
26,Distrito Federal,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332

In [19]:
comp = comp.merge(estado, on="Estado", how="inner")
comp

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1),total_x,total_branca_x,total_preta_parda_x,...,homem_preta_parda_x,mulher_branca_x,mulher_preta_parda_x,total_y,total_branca_y,total_preta_parda_y,homem_branca_y,homem_preta_parda_y,mulher_branca_y,mulher_preta_parda_y
0,AC,12,Acre,45.3,54.7,"53,2","46,8",13.606903,13.806929,13.541399,...,9.686983,16.130352,16.710754,13.606903,13.806929,13.541399,10.79612,9.686983,16.130352,16.710754
1,AL,27,Alagoas,44.7,55.3,"50,7","49,3",20.217129,19.165111,20.560451,...,13.35716,24.093655,25.856637,20.217129,19.165111,20.560451,12.121839,13.35716,24.093655,25.856637
2,AM,13,Amazonas,47.5,52.5,"46,8","53,2",16.80729,15.987545,16.995493,...,12.822584,18.764969,20.716986,16.80729,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
3,AP,16,Amapá,48.1,51.9,"51,1","48,9",13.586656,14.38918,13.415091,...,10.749444,16.648579,15.908487,13.586656,14.38918,13.415091,11.116821,10.749444,16.648579,15.908487
4,BA,29,Bahia,43.8,56.2,"44,7","55,3",17.849776,17.538007,17.935566,...,10.982808,22.57273,23.217119,17.849776,17.538007,17.935566,10.551673,10.982808,22.57273,23.217119
5,CE,23,Ceará,51.1,48.9,"52,7","47,3",19.499293,18.52712,19.882469,...,12.821323,23.019718,24.952274,19.499293,18.52712,19.882469,12.186936,12.821323,23.019718,24.952274
6,DF,53,Distrito Federal,41.0,59.0,"47,9","52,1",15.096351,15.061306,15.126295,...,10.481279,17.738123,19.307332,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332
7,ES,32,Espírito Santo,46.4,53.6,"47,5","52,5",17.111106,16.51061,17.478861,...,12.017589,20.464462,22.196626,17.111106,16.51061,17.478861,11.798571,12.017589,20.464462,22.196626
8,GO,52,Goiás,41.0,59.0,"47,5","52,5",15.186471,14.962622,15.296966,...,10.531883,18.440842,19.587913,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
9,MA,21,Maranhão,47.2,52.8,"49,1","50,9",16.669614,16.421773,16.708894,...,11.437359,19.881056,20.739589,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
10,MG,31,Minas Gerais,43.1,56.9,"48,6","51,4",17.502141,17.179387,17.707564,...,11.61912,22.18665,23.075751,17.502141,17.179387,17.707564,11.31972,11.61912,22.18665,23.075751
11,MS,50,Mato Grosso do Sul,47.2,52.8,"45,3","54,7",15.309783,14.902105,15.567204,...,11.12692,18.5932,19.542761,15.309783,14.902105,15.567204,10.446213,11.12692,18.5932,19.542761
12,MT,51,Mato Grosso,44.1,55.9,"42,8","57,2",14.239989,14.083513,14.270209,...,9.265734,17.782825,18.695923,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
13,PA,15,Pará,43.2,56.8,"48,3","51,7",16.474268,16.181627,16.560239,...,11.026707,19.83511,21.591144,16.474268,16.181627,16.560239,11.524306,11.026707,19.83511,21.591144
14,PB,25,Paraíba,44.4,55.6,"48,9","51,1",18.920816,18.88792,18.945306,...,12.400831,23.642936,24.03565,18.920816,18.88792,18.945306,12.480204,12.400831,23.642936,24.03565
15,PE,26,Pernambuco,43.9,56.1,"48,7","51,3",19.306249,18.950219,19.418444,...,12.868821,23.35788,24.243396,19.306249,18.950219,19.418444,12.312833,12.868821,23.35788,24.243396
16,PI,22,Piauí,51.2,48.8,"55,1","44,9",17.960366,16.948094,18.231789,...,11.204814,20.494063,23.69544,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.69544
17,PR,41,Paraná,40.3,59.7,"46,3","53,7",15.390122,15.453295,15.307289,...,10.815611,18.896661,19.36538,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.36538
18,RJ,33,Rio de Janeiro,44.2,55.8,"45,4","54,6",16.716263,16.097467,17.24306,...,12.864896,19.203741,20.957728,16.716263,16.097467,17.24306,12.000036,12.864896,19.203741,20.957728
19,RN,24,Rio Grande do Norte,51.0,49.0,"48,2","51,8",18.30774,18.101853,18.445218,...,11.086286,23.54708,24.422884,18.30774,18.101853,18.445218,11.166909,11.086286,23.54708,24.422884
20,RO,11,Rondônia,43.4,56.6,33,67,17.014162,16.727733,17.101523,...,12.54408,20.412887,21.06141,17.014162,16.727733,17.101523,12.111127,12.54408,20.412887,21.06141
21,RR,14,Roraima,41.8,58.2,"43,4","56,6",13.639257,13.651755,13.633606,...,10.476601,16.135877,16.560244,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
22,RS,43,Rio Grande do Sul,42.8,57.2,"47,4","52,6",15.356709,15.337269,15.448203,...,11.519941,18.86823,19.10772,15.356709,15.337269,15.448203,11.308447,11.519941,18.86823,19.10772
23,SC,42,Santa Catarina,42.7,57.3,"44,6","55,4",16.039355,16.124417,15.616235,...,11.517342,19.414764,19.646573,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
24,SE,28,Sergipe,46.5,53.5,"40,3","59,7",18.826541,17.264294,19.317934,...,11.270341,21.740902,25.637681,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
25,SP,35,São Paulo,45.4,54.6,"46,2","53,8",17.071295,16.964437,17.25548,...,12.2352,20.771186,21.76762,17.071295,16.964437,17.25548,12.123044,12.2352,20.771186,21.76762
26,TO,17,Tocantins,55.3,44.7,"46,2","53,8",15.815781,15.701788,15.768728,...,11.682616,19.663713,19.629399,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399

In [ ]:
ordem = comp.sort_values("mulheres_2026", ascending=False)["Estado"]

longo = comp.melt(
    id_vars=["Sigla", "Código", "Estado"],
    value_vars=["mulheres_2012", "mulheres_2026"],
    var_name="Ano",
    value_name="Participacao_mulheres",
)
longo["Ano"] = longo["Ano"].map({"mulheres_2012": "2012 T1", "mulheres_2026": "2026 T1"})

fig, ax = plt.subplots(figsize=(10, 10))
sns.barplot(
    data=longo,
    y="Estado",
    x="Participacao_mulheres",
    hue="Ano",
    order=ordem,
    ax=ax,
)
ax.axvline(50, color="gray", linestyle="--", linewidth=1)
ax.set_xlabel("Participação das mulheres entre as pessoas desocupadas (%)")
ax.set_ylabel("")
ax.set_title("Desocupação: participação feminina em 2012 T1 e 2026 T1")
ax.legend(title="Trimestre")
fig.tight_layout()
fig.savefig("participacao_mulheres_desocupacao.png", dpi=150)
plt.show()

In [ ]:
comp.to_csv("comp_tabela5_x_tabela1_1_1.csv", index=False)