In [6]:
import pandas as pd
!pip install openpyxl
import openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\12401030\appdata\roaming\python\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\12401030\appdata\roaming\python\python312\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 23.3.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
path = r"H:\Python\3°etapa\Atividade 4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [14]:
bruto = pd.read_excel(path, header=2)

In [15]:
bruto

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
trabalhado = bruto.iloc[0:5570, 1:]

In [17]:
trabalhado

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0

In [18]:
trabalhado.columns

Index(['UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022'],
      dtype='str')

In [19]:
trabalhado["diferença"] = trabalhado['População Censo 2022'] - trabalhado['População Município 2010\n(Sinopse)']

In [20]:
trabalhado

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferença
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0,-2898.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0,6480.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0,-962.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0,8313.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0,-1139.0
...,...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0,2408.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0,1397.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0,-520.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0,670.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0,247221.0

In [30]:
trabalhado.to_csv(r"H:\Python\3°etapa\Atividade 4\Trabalhado.csv", sep=";")

In [31]:
trabalhado.columns

Index(['UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022', 'diferença'],
      dtype='str')

In [32]:
estado = trabalhado.groupby("UF")[['População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022', 'diferença']].sum().reset_index()

In [33]:
estado

,UF,População 2010 (Alterações de Limites até 2022)1,População Censo 2022,diferença
0,AC,733559.0,830018.0,96459.0
1,AL,3120887.0,3127683.0,7189.0
2,AM,3483985.0,3941613.0,457628.0
3,AP,669526.0,733759.0,64233.0
4,BA,14017071.0,14141626.0,124720.0
5,CE,8451644.0,8794957.0,342576.0
6,DF,2572159.0,2817381.0,247221.0
7,ES,3514952.0,3833712.0,318760.0
8,GO,6001789.0,7056495.0,1052707.0
9,MA,6574789.0,6776699.0,201910.0
10,MG,19597330.0,20539989.0,942659.0
11,MS,2449024.0,2757013.0,307989.0
12,MT,3035122.0,3658649.0,623527.0
13,PA,7581051.0,8120131.0,539080.0
14,PB,3766528.0,3974687.0,208159.0
15,PE,8796055.0,9058931.0,262483.0
16,PI,3119097.0,3271199.0,152839.0
17,PR,10444526.0,11444380.0,999854.0
18,RJ,15989929.0,16055174.0,65245.0
19,RN,3168027.0,3302729.0,134702.0
20,RO,1562409.0,1581196.0,18787.0
21,RR,450479.0,636707.0,186228.0
22,RS,10693929.0,10882965.0,189036.0
23,SC,6248436.0,7610361.0,1361925.0
24,SE,2067852.0,2210004.0,141987.0
25,SP,41262199.0,44411238.0,3149039.0
26,TO,1383445.0,1511460.0,128015.0

In [34]:
estado.to_csv(r"H:\Python\3°etapa\Atividade 4\Estado.csv", sep=";")